CREATE FUNCTION FN_MONTAR_D_CALENDARIO (

@D_INI				DATE
,@D_FIM				DATE
,@ANO_FECHADO		BIT
,@INICIO_ANO_FISCAL INT

)
RETURNS @D_CALENDARIO TABLE (

[DATA]						DATE PRIMARY KEY
,ANO						INT
,DATA_INI_ANO				DATE
,DATA_FIM_ANO				DATE
,MES						TINYINT
,DATA_INI_MES				DATE
,DATA_FIM_MES				DATE
,DIAS_NO_MES				TINYINT
,ANO_MES					VARCHAR (8)
,DIA						TINYINT
,NOME_DIA_SEMANA			 VARCHAR(15)
,DIA_DA_SEMANA_ABREV		CHAR(3)
,DIA_SEMANA1				TINYINT
,DIA_ANO					SMALLINT
,NOME_MES					VARCHAR(30)
,NOME_MES_ABREV						CHAR(3)
,TRIMESTRE					INT
,NOME_TRIM					 VARCHAR(7)
,SEMANA_ANO					VARCHAR(30)
,INICIO_ANO_FISCAL			INT
,ANO_FISCAL					INT
,ANO_FISCAL2				INT

)

AS

BEGIN

--DECLARE @D_INI DATE = '10/07/2018';
--DECLARE @D_FIM DATE = '30/04/2022';

DECLARE @ANO_INI INT = YEAR(@D_INI);
DECLARE @ANO_FIM INT = YEAR(@D_FIM);
--DECLARE @INICIO_ANO_FISCAL INT = 7

SET @D_INI = DATEFROMPARTS(@ANO_INI, 1, 1);
SET @D_FIM = DATEFROMPARTS(@ANO_FIM, 12, 31);

;WITH DATAS AS (
    SELECT 
        DATEADD(DAY, A.SEQUENCIA - 1, @D_INI) AS [DATA]
    FROM 
        VEZES A
    WHERE 
        A.SEQUENCIA <= DATEDIFF(DAY, DATEFROMPARTS(@ANO_INI, 1, 1), DATEFROMPARTS(@ANO_FIM, 12, 31)) + 1
)
SELECT 
     [DATA]											AS [DATA]
    ,YEAR([DATA])									AS ANO
    ,DATEFROMPARTS(YEAR([DATA]), 1, 1)				AS DATA_INI_ANO
    ,DATEFROMPARTS(YEAR([DATA]), 12, 31)			AS DATA_FIM_ANO
    ,MONTH([DATA])									AS MES
    ,DATEFROMPARTS(YEAR([DATA]), MONTH([DATA]), 1)	AS DATA_INI_MES
    ,EOMONTH([DATA])								AS DATA_FIM_MES
    ,DAY(EOMONTH([DATA]))							AS DIAS_NO_MES
    ,CONCAT(
        YEAR([DATA]),
        CONCAT(
            REPLICATE('0', 2 - LEN(MONTH([DATA]))), 
            MONTH([DATA])
        )
    )												AS ANO_MES
	, DAY( [DATA] )									AS DIA
	, DATENAME(dw , [DATA] )						AS NOME_DIA_SEMANA
	, LEFT(DATENAME(dw , [DATA]),3)					AS DIA_DA_SEMANA_ABREV
	, DATEPART ( [WEEKDAY],[DATA] )					AS DIA_SEMANA1
	, DATEPART (dy, [DATA] )						AS DIA_ANO
	, DATENAME (mm, [DATA])							AS NOME_MES
	, LEFT(DATENAME (mm, [DATA]),3)					AS NOME_MES+ABREV
	, DATEPART(QQ,[DATA])							AS TRIMESTRE
	, CONCAT('T',DATEPART(QQ, [DATA]) )				AS NOME_TRIM
	,DATEPART(WK,[DATA])							AS SEMANA_ANO
	,CASE @INICIO_ANO_FISCAL						
	    WHEN 1 THEN YEAR([DATA])
		ELSE YEAR ([DATA] ) + CAST ( ( MONTH([DATA] ) + (13 - @INICIO_ANO_FISCAL )) / 13 AS INT)
	  END											AS INICIO_ANO_FISCAL
    , 13-@INICIO_ANO_FISCAL							AS ANO_FISCAL
	, CAST ( ( MONTH([DATA] ) + (13 - @INICIO_ANO_FISCAL )) / 13 AS INT) AS ANO_FISCAL2
FROM 
    DATAS;

	RETURN

	END
